name: Python application

on:
  push:
    branches: 
      - dev

env:
  REPO_NAME: shubh9975/images

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  development:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set HEAD SHA SHORT
            id: head_sha_short
            run: |
              echo "::set-output name=head_sha_short::$(git rev-parse --short HEAD)"
            shell: bash
          - name: Check HEAD SHA SHORT
            run: echo ${{ steps.head_sha_short.outputs.head_sha_short }}
            shell: bash
        
          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v4
            with:
              flavor: |
                latest=false
              images: ${{ env.REPO_NAME }}
              tags: |
                type=raw,value=${{ steps.head_sha_short.outputs.head_sha_short }}

          - name: Build and push the Docker image
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
          - uses: actions/checkout@v3
            name: changing the deployment of git repo
            with:
              repository: 'shubh9975/App-Manifest-'
              token: ${{ secrets.GIT_PASSWORD }}
          - name: modify the image
            run: |
              git config user.email shubham.tamboli1@gmail.com
              git config user.name Shubham
              pwd
              cat dev-env/dev-deployment.yaml
              pwd
              echo "commitID: ${{ env.COMMIT_SHA }}"
              #sed -i "s+shubh9975/images.*+shubh9975/images:${{ env.COMMIT_SHA }}+g" dev-env/dev-deployment.yaml
              sed -i "s+shubh9975/images.*+shubh9975/images:${{ env.COMMIT_SHA }}+g" dev-env/dev-deployment.yaml
              cat dev-env/dev-deployment.yaml
              git add .
              git commit -m 'Done  by Github Actions   Job change manifest: ${{ env.COMMIT_SHA }}'
              git push origin main
            env:
              GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
              GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
              RUN_NUMBER: ${{ github.run_number }}
              COMMIT_SHA: ${{ steps.meta.outputs.tags }}
